### ISSUE TITLE
i wonder if the python code of EEG Dataset for RSVP and P300 Speller Brain-Computer Interfaces is done？

### ISSUE THREAD

**Issue by Shin00324** [Kyungho-Won/EEG-dataset-for-RSVP-P300-speller#1]
52/5000 
I'm working on a similar project to yours and I'm having some problems. I don't know if your Python code is finished, because I see some of them are under modification。
Please reply to me if you can, I would appreciate it。

**Comment by Kyungho-Won** [comment]
Even though full functionality is implemented in Matlab, the current Python scripts can extract ERP and classify target vs. non-target EEG trials and test P300 speller. Under modification means that Python scripts are a bit messy so it could be better after organizing functions etc.

**Comment by Shin00324** [comment]
Thanks for the reply!
By the way,can any public dataset be applied to this code or do we need to use a specific dataset? Because I see that you seem to have a dataset in submission,i'm concerning about the format of the dataset i used(Actually download such a huge dataset take me quite a long time...)
