### ISSUE TITLE
Im facing a trouble while running this code in the file of 's01.mat' is not found or empty?

### ISSUE THREAD

**Issue by Mohamed-fawzyy** [Kyungho-Won/EEG-dataset-for-RSVP-P300-speller#2]

**Comment by Kyungho-Won** [comment]
Hello.

As written in readme,
You first need to download dataset.

Then please specify your path.

**Comment by Mohamed-fawzyy** [comment]
that is what I got after the mentioned steps,
![Screen Shot 2023-05-16 at 00 25 32 AM](https://github.com/KyunghoWon-GIST/EEG-dataset-for-RSVP-P300-speller/assets/111665714/47c54f17-764f-408e-935e-3b7c263c0258)

**Comment by Kyungho-Won** [comment]
Could you let me know the file size?. It is 253.45MB. if so, that should be working, or at least it should not produce this error as long as the path is correct.

**Comment by Mohamed-fawzyy** [comment]
actually, it's not the size of the zip code I've downloaded..
![Screen Shot 2023-05-16 at 00 32 13 AM](https://github.com/KyunghoWon-GIST/EEG-dataset-for-RSVP-P300-speller/assets/111665714/093a208e-feaa-4dca-aef7-de230ffb90aa)

**Comment by Kyungho-Won** [comment]
I think it failed to download whole dataset, as whole dataset is very huge, about 19GB.
You can download for each mat individually

**Comment by Mohamed-fawzyy** [comment]
okay, but I'm seeing all the files you uploaded here is the same as the files that I've downloaded so, even if I download them individually what is the difference?

**Comment by Kyungho-Won** [comment]
Another comment: you cannot load my mat files with scipy.io.loadmat. This function is for mat format other than mat73.
I saved the mat files using mat73, it requires mat73.loadmat or h5py. 
>> pip install mat73

Your script should be: 
>> eeg = mat73.loadmat('s01.mat')

**Comment by Kyungho-Won** [comment]
> okay, but I'm seeing all the files you uploaded here is the same as the files that I've downloaded so, even if I download them individually what is the difference?

I don't know, but your file size is only 433KB, somehow it does not represent my whole data

**Comment by Mohamed-fawzyy** [comment]
> Another comment: you cannot load my mat files with scipy.io.loadmat. This function is for mat format other than mat73. I saved the mat files using mat73, it requires mat73.loadmat or h5py.
> 
> > > pip install mat73
> 
> Your script should be:
> 
> > > eeg = mat73.loadmat('s01.mat')

ohh i got it, but i did both and nth.
Over all thank you😊

**Comment by Mohamed-fawzyy** [comment]
I apologize for the inconvenience caused, but I would like to inquire if there exists an alternative source or means to obtain the dataset, aside from utilizing GitHub or transmitting the file 's01.mat', in order to address the encountered error. I am actively seeking a resolution for this matter as the repository in question holds significant importance for my ongoing project.

**Comment by Mohamed-fawzyy** [comment]
I apologize for the inconvenience caused, but I would like to inquire if there exists an alternative source or means to obtain the dataset, aside from utilizing GitHub or transmitting the file 's01.mat', in order to address the encountered error. I am actively seeking a resolution for this matter as the repository in question holds significant importance for my ongoing project.

**Comment by Mohamed-fawzyy** [comment]
I apologize for the inconvenience caused, but I would like to inquire if there exists an alternative source or means to obtain the dataset, aside from utilizing GitHub or transmitting the file 's01.mat', in order to address the encountered error. I am actively seeking a resolution for this matter as the repository in question holds significant importance for my ongoing project.
